menu:
  Home: /
  Archives: /archives
  About: /adout
rss: /atom.xml

favicon: images/favicon.png

avatar: images/favicon.png

# 代码高亮设置
# Code Highlight theme
# Available value:
#   normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://github.com/xCss/Valine
valine:
  enable: true
  appid:  ih2nzG3ilVNdLgJK4kBXTjOq-gzGzoHsz # your leancloud application appid
  appkey: gdf6tXXLBTLg9qpjS2y6Tbw7 # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 评论一下再走吧~